---
title: "App_sketches"
author: "Hanif Wicaksono"
date: "11/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(sf)
library(fs)
library(ggthemes)
library(janitor)
library(tidyverse)
```

## This document is NOT meant to be knitted

## Read objects from shiny rds

```{r read_objects_shiny}

neighborhoods_map <-
  read_rds(path = "cambridge-energy-use/shiny-data/neighborhoods.rds")

parcel_index_map <-
  read_rds(path = "cambridge-energy-use/shiny-data/parcel_index.rds")

parcel_map <-
  read_rds(path = "cambridge-energy-use/shiny-data/parcels.rds")

energy_use <-
  read_rds(path = "cambridge-energy-use/shiny-data/energyuse.rds")

energy_source <-
  read_rds(path = "cambridge-energy-use/shiny-data/energy_source.rds")

energy_map <-
  read_rds(path = "cambridge-energy-use/shiny-data/energy_map.rds")
```

## Below is unorganized R sketches to write objects and testing out visualizations

```{r}
energy_use %>%
  filter(report_type != "Child" & reporting_year == 2018) %>%
  group_by(primary_property_type_self_selected) %>%
  count() %>%
  arrange(desc(n))
```


```{r}


# Laboratory Regression
 

x <- energy_use 

x[is.na(x)] <- "NA"
```

```{r}
a <- "College/University"
b <- "Multifamily Housing"
c <- "Office"
d <- "Laboratory"

min_built = 1800
max_built = 2016

x_plot <- 
   
  x %>%
  filter(report_type != "Child" & reporting_year == 2018) %>%
  mutate(renewable_use = ifelse(electricity_use_generated_from_onsite_renewable_systems_k_wh != is.na(electricity_use_generated_from_onsite_renewable_systems_k_wh), 1, 0),
         total_kbtu = as.numeric(source_energy_use_k_btu),
         as.logical(renewable_use)) %>%
  filter(primary_property_type_self_selected == b,
         year_built > min_built & year_built < max_built) %>%
  ggplot(aes(x = year_built, y = total_kbtu, color = renewable_use)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  theme(legend.position = "none")

x_plot
```


```{r energy_map_prep}
energy_map <-
  read_rds(path = "cambridge-energy-use/shiny-data/energyuse.rds") %>%
  separate(col = map_lot, into = c("parcel_index", "parcel_id"), sep = "-") %>%
  filter(report_type != "Child") %>%
  select(reporting_year,
         parcel_index, 
         grantee, 
         source_energy_use_k_btu, 
         source_eui_k_btu_ft2,
         total_ghg_emissions_metric_tons_co2e,
         total_ghg_emissions_intensity_kg_co2e_ft2,
         water_use_all_water_sources_kgal,
         water_intensity_all_water_sources_gal_ft2
         )

energy_map[is.na(energy_map)] <- 0

write_rds(x = energy_map, path = "cambridge-energy-use/shiny-data/energy_map.rds")


energy_sf <-
  energy_map %>%
  filter(reporting_year == 2018) %>%
  mutate(PCIX_NO = parcel_index) %>%
  group_by(PCIX_NO) %>%
  summarize(parcel_energy_use = sum(source_energy_use_k_btu),
            parcel_energy_intensity = sum(source_eui_k_btu_ft2),
            parcel_ghg_emission = sum(total_ghg_emissions_metric_tons_co2e),
            parcel_ghg_intensity = sum(total_ghg_emissions_intensity_kg_co2e_ft2),
            parcel_water_use = sum(water_use_all_water_sources_kgal),
            parcel_water_intensity = sum(water_intensity_all_water_sources_gal_ft2)) %>%
  right_join(x = energy_sf, y = parcel_index_map, by = "PCIX_NO") %>%
  st_as_sf()

write_rds(x = energy_sf, path = "cambridge-energy-use/shiny-data/energy_map.rds")
```

```{r energy_map_plot}

energy_sf %>%
  ggplot() +
  geom_sf(aes(fill = parcel_energy_use)) +
            labs(
                title = "Cambridge MA Parcels",
                subtitle = "Official 2019 Boundaries",
                caption = "Data source: City of Cambridge, MA"
            )

```


```{r data_prep}
energyuse <-
  read_csv(file = "raw-data/Cambridge_Building_Energy_and_Water_Use_Data_Disclosure_2016-2018.csv") %>%
  clean_names()

energyuse %>%
  write_rds(path = "clean-data/energyuse.rds")

file_copy(path = "clean-data/energyuse.rds", 
          new_path = "cambridge-energy-use/shiny-data/energyuse.rds")
```

```{r}
energyuse[is.na(energyuse)] <- 0

# min_built = input$year_built[1]
# max_built = input$year_built[2]

energy_source <-
  energyuse %>%
  filter(primary_property_type_self_selected != 0,
         reporting_year == 2018,
         report_type != "Child") %>%
  group_by(primary_property_type_self_selected) %>%
  summarize(n_buildings = n(),
            grid_electricity = sum(electricity_use_grid_purchase_k_btu),
            natural_gas = sum(natural_gas_use_k_btu),
            fuel_oil = sum(fuel_oil_number_1_use_k_btu + fuel_oil_number_2_use_k_btu + 
                             fuel_oil_number_4_use_k_btu + fuel_oil_number_5_6_use_k_btu),
            diesel = sum(diesel_number_2_use_k_btu),
            kerosene = sum(kerosene_use_k_btu),
            total_kbtu = grid_electricity + natural_gas + fuel_oil + diesel + kerosene) %>%
  select(primary_property_type_self_selected, 
         n_buildings,
         grid_electricity, 
         natural_gas,
         fuel_oil,
         diesel,
         kerosene,
         total_kbtu)

write_rds(x = energy_source, path = "clean-data/energy_source.rds")

file_copy(path = "clean-data/energy_source.rds", 
          new_path = "cambridge-energy-use/shiny-data/energy_source.rds")
```

```{r}
grid_electricity = energy_source$grid_electricity
natural_gas = energy_source$natural_gas
fuel_oil = energy_source$fuel_oil
diesel = energy_source$diesel
kerosene = energy_source$kerosene
total_kbtu = energy_source$total_kbtu

selected_source <- c(grid_electricity, 
                     natural_gas, 
                     fuel_oil, 
                     diesel, 
                     kerosene, 
                     total_kbtu)

  energy_source %>%
  ggplot(aes(area = source_type, 
             fill = primary_property_type_self_selected, 
             label = primary_property_type_self_selected)) +
  geom_treemap() +
  geom_treemap_text() +
  theme(legend.position = "none")
```


```{r energy_source}

energyuse[is.na(energyuse)] <- 0

energyuse %>%
            filter(reporting_year == 2018, 
                   report_type != "Child") %>%
  group_by(electricity_use_generated_from_onsite_renewable_systems_k_wh) %>%
  summarize(n = n()) %>%
  mutate(renewable = ifelse(n != 1, "no", "yes")) %>%
  select(n, renewable) %>%
  group_by(n) %>%
  summarize(yes = n()) %>%
  mutate(n_renewable = n + yes,
         total = sum(n_renewable),
         prop_renewable = n_renewable/total) %>%
  mutate(labels = c("Generate any renewable", "Doesn't generate any on-site renewable")) %>%
  ggplot(aes(area = prop_renewable, fill = labels, label = labels)) + 
  theme(legend.position = "none") +
  geom_treemap() +
  geom_treemap_text(place = "centre", grow = TRUE)
  

```



```{r who consume}

#input$energy_year

energyuse %>%
  filter(reporting_year == 2017, 
         report_type != "Child", 
         electricity_use_grid_purchase_k_wh != "NA") %>%
  group_by(property_type) %>%
  summarize(sumKwh = sum(electricity_use_grid_purchase_k_wh)) %>%
  mutate(total = sum(sumKwh)) %>%
  mutate(percentage = sumKwh / total) %>%
  ggplot(aes(x = property_type, y = sumKwh)) +
  geom_col(aes(fill = property_type))

energyuse %>%
  filter(reporting_year == 2016, 
         report_type != "Child", 
         water_use_all_water_sources_kgal != "NA"
         ) %>%
  group_by(property_type) %>%
  summarize(sumKgal = sum(water_use_all_water_sources_kgal)) %>%
  mutate(total = sum(sumKgal)) %>%
  mutate(percentage = sumKgal / total) %>%
  ggplot(aes(x = property_type, y = sumKgal)) +
  geom_col(aes(fill = property_type))
           
  
```

```{r data_write}

energyuse <-
  read_rds(path = "cambridge-energy-use/shiny-data/energyuse.rds")

# min_built = input$year_built[1]
# max_built = input$year_built[2]

min_built = 1700
max_built = 2016

energyuse %>%
  filter(reporting_year == 2018, report_type != "Child") %>%
  filter(year_built > min_built & year_built < max_built) %>%
  ggplot(aes(x = year_built)) +
  geom_histogram(aes(fill = property_type))
```

```{r}

#year = input$energy_year

year = 2018

energyuse %>%
  filter(reporting_year == year, report_type != "Child") %>%
  group_by(property_type) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
```

```{r map_prep}

parcels_shp <- 
  st_read("raw-data/parcels/") %>%
  st_as_sf()

write_rds(parcels_shp, path = "clean-data/parcels.rds")

neighborhoods <- 
  st_read("raw-data/neighborhoods/") %>%
  st_as_sf()

write_rds(neighborhoods, path = "clean-data/neighborhoods.rds")

parcel_index <- 
  st_read("raw-data/index/") %>%
  st_as_sf()

write_rds(parcel_index, path = "clean-data/parcel_index.rds")
```

```{r map_write}

# Read data

parcels_shp <- 
  read_rds("clean-data/parcels.rds") %>%
  clean_names()

parcels_shp <- 
  parcels_shp %>%
  mutate(map_lot = ml) %>%
  select(map_lot, shape_st_ar, shape_st_le, geometry)

parcel_index <-
  parcel_index %>%
  clean_names()

```


```{r shiny_export}
file_delete(path = "cambridge-energy-use/shiny-data/")

dir_create(path = "cambridge-energy-use/shiny-data")

file_copy(path = "clean-data/neighborhoods.rds", 
          new_path = "cambridge-energy-use/shiny-data/neighborhoods.rds")

file_copy(path = "clean-data/parcels.rds", 
          new_path = "cambridge-energy-use/shiny-data/parcels.rds")

file_copy(path = "clean-data/parcel_index.rds", 
          new_path = "cambridge-energy-use/shiny-data/parcel_index.rds")


# Read rds cleaned

parcels_shp <- 
        read_rds("cambridge-energy-use/shiny-data/parcels.rds") %>%
        clean_names() %>%
        mutate(map_lot = ml) %>%
        select(map_lot, shape_st_ar, shape_st_le, geometry)
    
    parcel_index_shp <- 
        read_rds("cambridge-energy-use/shiny-data/parcel_index.rds") %>%
        clean_names()
    
    neighborhoods_shp <- 
        read_rds("cambridge-energy-use/shiny-data/neighborhoods.rds") %>%
        clean_names()

```


```{r map_viz}

ggplot() +
  # geom_sf(data = parcels_shp) +
  geom_sf(data = parcel_index)
  # geom_sf(data = neighborhoods_shp, color = "red", alpha = 0)

```


